resource "oci_core_drg" "export_DRG-Phoenix" {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  display_name   = "DRG-Phoenix"
  freeform_tags = {
  }
}

resource oci_core_route_table export_SVCN-PHOENIX-DRG-RT {
  compartment_id = var.compartment_ocid
  display_name = "SVCN-PHOENIX-DRG-RT"
  freeform_tags = {
  }
#   route_rules {
#     destination       = "0.0.0.0/0"
#     destination_type  = "CIDR_BLOCK"
#     network_entity_id = "ocid1.privateip.oc1.phx.abyhqljtfupvepkiz23vv2xif42fhxivdoy2if2styz44eje2yvd4mdo6mqa"
#   }
  vcn_id = oci_core_vcn.export_phoenix-svcn.id
}

resource "oci_core_drg_attachment" "export_SVCN-HUB-Phoenix" {
  display_name       = "SVCN-HUB-Phoenix"
  drg_id             = oci_core_drg.export_DRG-Phoenix.id
  drg_route_table_id = oci_core_drg_route_table.export_DRG-PHOENIX-HUB-RT.id
  #export_drg_route_distribution_id = <<Optional value not found in discovery>>
  freeform_tags = {
  }

  route_table_id = oci_core_route_table.export_SVCN-PHOENIX-DRG-RT.id
  vcn_id = oci_core_vcn.export_phoenix-svcn.id
}

resource "oci_core_drg_attachment" "export_phoenix-vcn-attachment" {
  defined_tags = {
  }
  display_name       = "phoenix-vcn-attachment"
  drg_id             = oci_core_drg.export_DRG-Phoenix.id
  drg_route_table_id = oci_core_drg_route_table.export_DRG-PHOENIX-SPOKE-RT.id
  freeform_tags = {
  }
  vcn_id = oci_core_vcn.export_phoenix-vcn.id
}

resource "oci_core_drg_route_distribution" "export_HUB-IMPORT-RULES" {
  display_name      = "HUB-IMPORT-RULES"
  distribution_type = "IMPORT"
  drg_id            = oci_core_drg.export_DRG-Phoenix.id
  freeform_tags = {
  }
}

resource "oci_core_drg_route_distribution_statement" "route-import-statement-1" {
    #Required
    drg_route_distribution_id = oci_core_drg_route_distribution.export_HUB-IMPORT-RULES.id
    action = "ACCEPT"
    match_criteria {
    #Required
    match_type = "DRG_ATTACHMENT_ID"
    drg_attachment_id = oci_core_drg_attachment.export_phoenix-vcn-attachment.id
    }
    priority = 10

}

resource "oci_core_drg_route_distribution_statement" "route-import-statement-2" {
    #Required
    drg_route_distribution_id = oci_core_drg_route_distribution.export_HUB-IMPORT-RULES.id
    action = "ACCEPT"
    match_criteria {
    #Required
    match_type = "DRG_ATTACHMENT_ID"
    drg_attachment_id = oci_core_drg_attachment.export_SVCN-HUB-Phoenix.id
    }
    priority = 20

}

resource "oci_core_drg_route_distribution" "export_Autogenerated-Import-Route-Distribution-for-ALL-routes" {
  defined_tags = {
  }
  display_name      = "Autogenerated Import Route Distribution for ALL routes"
  distribution_type = "IMPORT"
  drg_id            = oci_core_drg.export_DRG-Phoenix.id
  freeform_tags = {
  }
}

resource "oci_core_drg_route_distribution" "export_Autogenerated-Import-Route-Distribution-for-VCN-Routes" {
  defined_tags = {
  }
  display_name      = "Autogenerated Import Route Distribution for VCN Routes"
  distribution_type = "IMPORT"
  drg_id            = oci_core_drg.export_DRG-Phoenix.id
  freeform_tags = {
  }
}

resource "oci_core_drg_route_table" "export_DRG-PHOENIX-RPC-RT" {
  display_name = "DRG-PHOENIX-RPC-RT"
  drg_id       = oci_core_drg.export_DRG-Phoenix.id
  freeform_tags = {
  }
  import_drg_route_distribution_id = oci_core_drg_route_distribution.export_HUB-IMPORT-RULES.id
  is_ecmp_enabled                  = "false"
}

resource "oci_core_drg_route_table" "export_DRG-PHOENIX-SPOKE-RT" {
  display_name = "DRG-PHOENIX-SPOKE-RT"
  drg_id       = oci_core_drg.export_DRG-Phoenix.id
  freeform_tags = {
  }
  is_ecmp_enabled = "false"
}

resource "oci_core_drg_route_table" "export_DRG-PHOENIX-HUB-RT" {
  display_name = "DRG-PHOENIX-HUB-RT"
  drg_id       = oci_core_drg.export_DRG-Phoenix.id
  freeform_tags = {
  }
  import_drg_route_distribution_id = oci_core_drg_route_distribution.export_HUB-IMPORT-RULES.id
  is_ecmp_enabled                  = "false"
}

resource "oci_core_drg_route_table" "export_Autogenerated-Drg-Route-Table-for-VCN-attachments" {
  display_name = "Autogenerated Drg Route Table for VCN attachments"
  drg_id       = oci_core_drg.export_DRG-Phoenix.id
  freeform_tags = {
  }
  import_drg_route_distribution_id = oci_core_drg_route_distribution.export_Autogenerated-Import-Route-Distribution-for-ALL-routes.id
  is_ecmp_enabled                  = "false"
}

resource "oci_core_drg_route_table" "export_Autogenerated-Drg-Route-Table-for-RPC-VC-and-IPSec-attachments" {
  display_name = "Autogenerated Drg Route Table for RPC, VC, and IPSec attachments"
  drg_id       = oci_core_drg.export_DRG-Phoenix.id
  freeform_tags = {
  }
  import_drg_route_distribution_id = oci_core_drg_route_distribution.export_Autogenerated-Import-Route-Distribution-for-VCN-Routes.id
  is_ecmp_enabled                  = "false"
}

resource "oci_core_drg_route_table_route_rule" "export_DRG-PHOENIX-SPOKE-RT_drg_route_table_route_rule" {
  destination                = "0.0.0.0/0"
  destination_type           = "CIDR_BLOCK"
  drg_route_table_id         = oci_core_drg_route_table.export_DRG-PHOENIX-SPOKE-RT.id
  next_hop_drg_attachment_id = oci_core_drg_attachment.export_SVCN-HUB-Phoenix.id
}