resource oci_core_drg export_DRG-SJC {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  display_name = "DRG-SJC"
  freeform_tags = {
  }
}

resource oci_core_drg_attachment export_spoke-vcn-b-drg-attatch {
  defined_tags = {
  }
  display_name       = "spoke-vcn-b-drg-attatch"
  drg_id             = oci_core_drg.export_DRG-SJC.id
  drg_route_table_id = oci_core_drg_route_table.export_DRG-SPOKE-RT.id
  freeform_tags = {
  }
  vcn_id = oci_core_vcn.export_spoke-vcn-b.id
}

resource oci_core_drg_attachment export_spoke-vcn-a-drg-attatch {
  defined_tags = {
  }
  display_name       = "spoke-vcn-a-drg-attatch"
  drg_id             = oci_core_drg.export_DRG-SJC.id
  drg_route_table_id = oci_core_drg_route_table.export_DRG-SPOKE-RT.id
  freeform_tags = {
  }
  vcn_id = oci_core_vcn.export_spoke-vcn-a.id
}

resource oci_core_drg_attachment export_svc-vcn-drg-attatch {
  defined_tags = {
  }
  display_name       = "svc-vcn-drg-attatch"
  drg_id             = oci_core_drg.export_DRG-SJC.id
  drg_route_table_id = oci_core_drg_route_table.export_DRG-HUB-RT.id
  freeform_tags = {
  }
  route_table_id = oci_core_route_table.export_vcn-drg-rt.id
  vcn_id         = oci_core_vcn.export_mcd-svcn.id
}

resource oci_core_drg_route_distribution export_HUB-IMPORT-RULES {
  display_name      = "HUB-IMPORT-RULES"
  distribution_type = "IMPORT"
  drg_id            = oci_core_drg.export_DRG-SJC.id
  freeform_tags = {
  }
}

resource "oci_core_drg_route_distribution_statement" "route-import-statement-1" {
    #Required
    drg_route_distribution_id = oci_core_drg_route_distribution.export_HUB-IMPORT-RULES.id
    action = "ACCEPT"
    match_criteria {
    #Required
    match_type = "DRG_ATTACHMENT_ID"
    drg_attachment_id = oci_core_drg_attachment.export_spoke-vcn-a-drg-attatch.id
    }
    priority = 10

}

resource "oci_core_drg_route_distribution_statement" "route-import-statement-2" {
    #Required
    drg_route_distribution_id = oci_core_drg_route_distribution.export_HUB-IMPORT-RULES.id
    action = "ACCEPT"
    match_criteria {
    #Required
    match_type = "DRG_ATTACHMENT_ID"
    drg_attachment_id = oci_core_drg_attachment.export_spoke-vcn-b-drg-attatch.id
    }
    priority = 20

}

resource "oci_core_drg_route_distribution_statement" "route-import-statement-3" {
    #Required
    drg_route_distribution_id = oci_core_drg_route_distribution.export_HUB-IMPORT-RULES.id
    action = "ACCEPT"
    match_criteria {
    #Required
    match_type = "DRG_ATTACHMENT_ID"
    drg_attachment_id = oci_core_drg_attachment.export_svc-vcn-drg-attatch.id
    }
    priority = 30

}

resource oci_core_drg_route_distribution export_Autogenerated-Import-Route-Distribution-for-ALL-routes {
  defined_tags = {
  }
  display_name      = "Autogenerated Import Route Distribution for ALL routes"
  distribution_type = "IMPORT"
  drg_id            = oci_core_drg.export_DRG-SJC.id
  freeform_tags = {
  }
}

resource oci_core_drg_route_distribution export_Autogenerated-Import-Route-Distribution-for-VCN-Routes {
  defined_tags = {
  }
  display_name      = "Autogenerated Import Route Distribution for VCN Routes"
  distribution_type = "IMPORT"
  drg_id            = oci_core_drg.export_DRG-SJC.id
  freeform_tags = {
  }
}

resource oci_core_drg_route_table export_DRG-SJC-RPC-RT {

  display_name = "DRG-SJC-RPC-RT"
  drg_id       = oci_core_drg.export_DRG-SJC.id
  freeform_tags = {
  }
  import_drg_route_distribution_id = oci_core_drg_route_distribution.export_HUB-IMPORT-RULES.id
  is_ecmp_enabled                  = "false"
}

resource oci_core_drg_route_table export_DRG-HUB-RT {

  display_name = "DRG-HUB-RT"
  drg_id       = oci_core_drg.export_DRG-SJC.id
  freeform_tags = {
  }
  import_drg_route_distribution_id = oci_core_drg_route_distribution.export_HUB-IMPORT-RULES.id
  is_ecmp_enabled                  = "false"
}

resource oci_core_drg_route_table export_DRG-SPOKE-RT {

  display_name = "DRG-SPOKE-RT"
  drg_id       = oci_core_drg.export_DRG-SJC.id
  freeform_tags = {
  }
  is_ecmp_enabled = "false"
}

resource oci_core_drg_route_table export_Autogenerated-Drg-Route-Table-for-VCN-attachments {

  display_name = "Autogenerated Drg Route Table for VCN attachments"
  drg_id       = oci_core_drg.export_DRG-SJC.id
  freeform_tags = {
  }
  import_drg_route_distribution_id = oci_core_drg_route_distribution.export_Autogenerated-Import-Route-Distribution-for-ALL-routes.id
  is_ecmp_enabled                  = "false"
}

resource oci_core_drg_route_table export_Autogenerated-Drg-Route-Table-for-RPC-VC-and-IPSec-attachments {

  display_name = "Autogenerated Drg Route Table for RPC, VC, and IPSec attachments"
  drg_id       = oci_core_drg.export_DRG-SJC.id
  freeform_tags = {
  }
  import_drg_route_distribution_id = oci_core_drg_route_distribution.export_Autogenerated-Import-Route-Distribution-for-VCN-Routes.id
  is_ecmp_enabled                  = "false"
}

resource oci_core_drg_route_table_route_rule export_DRG-SPOKE-RT_drg_route_table_route_rule {
  destination                = "0.0.0.0/0"
  destination_type           = "CIDR_BLOCK"
  drg_route_table_id         = oci_core_drg_route_table.export_DRG-SPOKE-RT.id
  next_hop_drg_attachment_id = oci_core_drg_attachment.export_svc-vcn-drg-attatch.id
}

resource oci_core_drg_route_table_route_rule export_Autogenerated-Drg-Route-Table-for-RPC-VC-and-IPSec-attachments_drg_route_table_route_rule {
  destination                = "0.0.0.0/0"
  destination_type           = "CIDR_BLOCK"
  drg_route_table_id         = oci_core_drg_route_table.export_Autogenerated-Drg-Route-Table-for-RPC-VC-and-IPSec-attachments.id
  next_hop_drg_attachment_id = oci_core_drg_attachment.export_svc-vcn-drg-attatch.id
}